docs: autorec.py docstring 추가
otzslayer/deeprecs pull request #2
Opened 2022-06-29 06:32 UTC by kwonskdev

- Encoder, Decoder, AutoRec class의 docstring 추가
- pre-commit-config 파일에서 super-init-not-called를 disable에 추가

2022-06-29 06:34 UTC, kwonskdev commented
BaseRecommender에 __init__ 작성후 subclass에서 다 super().__init__() 사용하거나, super-init-not-called를 disable하거나 해야하는데 disable이 나은거 같아서 disable로 처리했습니다. 다른 의견 있으면 말씀해주세요

2022-06-30 01:05 UTC, otzslayer requested changes
- AutoRec 모델인데 AutoRec의 특징이 없는 듯 싶습니다.
물론 AutoRec이 너무 초창기 모델이라 1-layer encoder/decoder 여서 범용성이 낮다지만 레이어가 stacked되는 순간 AutoRec 보다는 CDL(Collaborative Deep Learning)에 가까워지는 느낌입니다.
기존 논문을 어디까지 자의적으로 해석하여도 되는지에 대한 논의가 필요해 보이네요.
- Encoder와 Decoder를 굳이 클래스화하신 이유를 잘 모르겠습니다.
물론 개발하신 의도대로 확장된 의미에서의 AutoRec 이라면 괜찮을 수도 있겠습니다만...
- 일부 수정 부분은 pylint 때문에 억지로 하신 부분이 보이는데,
그런 경우엔 코멘트 해주세요.

다른 분들의 의견이 궁금하네요.

2022-06-30 01:05 UTC, otzslayer commented on .pre-commit-config.yaml
> +            "unexpected-keyword-arg,no-value-for-parameter,too-many-function-args,missing-module-docstring,wildcard-import,super-init-not-called",
전 pylint 원래처럼 설정하고 `BaseRecommender`에서 `super-init-not-called` 에러는 안떴는데, 혹시 모델에서만 `super(class_name, self).__init__()` 안해서 해당 에러가 뜨던가요?
만약에 새로 만드신 모델에서만 `super-init-not-called`가 뜨신거라면 반드시 `super(class_name, self).__init__()` 해주시는게 맞습니다.

2022-06-30 01:05 UTC, otzslayer commented on deeprecs/models/base.py
> +    def forward(self, input_data):
혹시 이것도 pylint 에러 때문에 그러신가요?
그러신거면 그냥 추상 메서드 부분을 `def forward(self, *args, **kwargs)`로 하는게 나을 것 같아요. 
다른 모델들은 단순히 `input_data`만 받진 않으니까요.

2022-06-30 02:24 UTC, kwonskdev commented on .pre-commit-config.yaml
> +            "unexpected-keyword-arg,no-value-for-parameter,too-many-function-args,missing-module-docstring,wildcard-import,super-init-not-called",
BaseRecommender의 sub class의 __init__을 쓸거면 무조건 BaseRecommender의 __init__을 쓰게 되어있더라구요 (안쓰면 에러) 근데 BaseRecommender에 __init__을 넣어도 빈 껍데기일텐데 그걸 계속 super(class_name, self).__init__()하는게 의미 없어 보여서 걍 disable 햇습니다. 바꿔야되면 제가 base recommender에 빈 껍데기로 __init__ 추가하겠습니다.

2022-06-30 02:24 UTC, kwonskdev commented on deeprecs/models/base.py
> +    def forward(self, input_data):
넵 수정하겠습니다

2022-06-30 02:26 UTC, kwonskdev commented
@otzslayer 

> * AutoRec 모델인데 AutoRec의 특징이 없는 듯 싶습니다.
>   물론 AutoRec이 너무 초창기 모델이라 1-layer encoder/decoder 여서 범용성이 낮다지만 레이어가 stacked되는 순간 AutoRec 보다는 CDL(Collaborative Deep Learning)에 가까워지는 느낌입니다.
>   기존 논문을 어디까지 자의적으로 해석하여도 되는지에 대한 논의가 필요해 보이네요.
> * Encoder와 Decoder를 굳이 클래스화하신 이유를 잘 모르겠습니다.
>   물론 개발하신 의도대로 확장된 의미에서의 AutoRec 이라면 괜찮을 수도 있겠습니다만...
> * 일부 수정 부분은 pylint 때문에 억지로 하신 부분이 보이는데,
>   그런 경우엔 코멘트 해주세요.
> 
> 다른 분들의 의견이 궁금하네요.

2022-06-30 04:20 UTC, otzslayer commented on .pre-commit-config.yaml
> +            "unexpected-keyword-arg,no-value-for-parameter,too-many-function-args,missing-module-docstring,wildcard-import,super-init-not-called",
이건 저도 좀 확인하겠습니다. 
그런데 `BaseRecommender`에 `super(BaseRecommender, self).__init__()` 하는게 나을 것 같네요.
사실 보통 추상클래스엔 이걸 잘 안하는걸로 알고 있는데 scikit-learn 좀 살펴봐야겠어요.

2022-06-30 04:22 UTC, otzslayer commented
걸어주신 링크는 CDL이 아니라 NCF네요.
CDL 논문은 [이걸](https://arxiv.org/pdf/1409.2944.pdf) 참고하시면 될 것 같습니다.
제 생각엔 일단 AutoRec을 구현한 다음에 말씀하신 Unsymmetric한 형태의 구현을 별도로 하는게 좋은 듯 합니다.

2022-06-30 04:30 UTC, otzslayer commented on .pre-commit-config.yaml
> +            "unexpected-keyword-arg,no-value-for-parameter,too-many-function-args,missing-module-docstring,wildcard-import,super-init-not-called",
https://github.com/scikit-learn/scikit-learn/blob/main/sklearn/ensemble/_forest.py#L673-L710
`BaseRecommender`에도 `__init__` 해야겠네요. :/

2022-06-30 04:33 UTC, HeainLee commented on .pre-commit-config.yaml
> +            "unexpected-keyword-arg,no-value-for-parameter,too-many-function-args,missing-module-docstring,wildcard-import,super-init-not-called",
부모 클래스에 __init__이 설정되어 있어야 상속 받는 클래스 __init__을 쓸 수 있고, 그럴 경우 현재 베이스 클래스로 정의한 BaseRecommender 에서 __init__ 을 추가하되 상속 받는 클래스에서 부모 클래스의 __init__ 메소드를 굳이 호출하지 않고 사용하면 되지 않을까요? 또한, 현재로서는 BaseRecommender 의 __init__ 에 아직은 정의된 게 없는 상태겠지만, AutoRec 이외에 다른 모델들을 구현하는 과정에 BaseRecommender 의 __init__ 에  추가되어 코드 중복의 회피하고 추상화할 수 있는 부분이 생긴다면 추후에 정리해보면 어떨까 합니다.

2022-06-30 05:37 UTC, kwonskdev commented on .pre-commit-config.yaml
> +            "unexpected-keyword-arg,no-value-for-parameter,too-many-function-args,missing-module-docstring,wildcard-import,super-init-not-called",
넵 그럼 일단 `BaseRecommeder`에 껍데기로 `__init__` 추가하겠습니다.
나중에 다른 모델들이랑 중복 회피할 수 있는 부분 있으면 그 때 정리하면 될 것 같습니다.

2022-06-30 05:46 UTC, kwonskdev commented
- CDL이 결국 SDAE에서 발전된 형태 같습니다. CDL도 AutoREC의 sub class도 만들던가 하겠습니다.
- 모델의 Input 형태라는게 `__init__`의 파라미터 말씀하시는거죠? 
AutoREC은 1-layer encoder/decoder로 input으로 다른 모델들과 완전 똑같이 만들고, 이후에 StackedAutoRec이나 CDL 등 다른 sub_class의 `__init__`에선 자유롭게 하라는 말씀이신건가요? 
다른 sub_class들도 `__init__`의 파라미터를 공통으로 하면 layer를 고정시켜놓아야 하는데 그러면 사용자 입장에서 너무 불편할 거 같습니다.

2022-06-30 05:50 UTC, otzslayer commented
> * 모델의 Input 형태라는게 `__init__`의 파라미터 말씀하시는거죠?
넵. 맞습니다.

>   AutoREC은 1-layer encoder/decoder로 input으로 다른 모델들과 완전 똑같이 만들고, 이후에 StackedAutoRec이나 CDL 등 다른 sub_class의 `__init__`에선 자유롭게 하라는 말씀이신건가요?
>   다른 sub_class들도 `__init__`의 파라미터를 공통으로 하면 layer를 고정시켜놓아야 하는데 그러면 사용자 입장에서 너무 불편할 거 같습니다.
음. 원래 모든 모델들에 들어가는 init params는 `num_users`, `num_items`, `num_hidden_layers`, `num_hidden_units` 같은 것들만 들어간다고 생각해서요. 지금 개발하신 형태로 보면 `encoder_layers`, `num_encoder_units`, `decoder_layers`, `num_decoder_units` 처럼 넣을 수 있지 않나 싶어서요.

2022-06-30 05:53 UTC, kwonskdev commented
파라미터에 들어가는 건 int나 list처럼 파이썬 내장 클래스만 사용하라는 말씀이신거죠? 그렇게 수정하겠습니다

2022-06-30 06:35 UTC, HeainLee commented
변경된 코드에 대해 현재까지의 위 리뷰 내용(w/코멘트)에 동의합니다. 추가 코멘트가 하나 있습니다. 

-  models 폴더 내 스크립트 구현 관련 : 각 추천 모델들을 클래스로 구현했을 때 main.py를 어떻게 구성해서 모델을 선언할지가 정해지지 않아서 모델 클래스의 __init__ 구성이 제각각이 될 수 있겠다는 생각이 들었습니다.  (지금의 경우도, encoder와 decoder를 클래스로 만들어서 AutoRec의 인자로 넣어주는 형태라면, main.py에서 encoder와 decoder 클래스를 선언해줘야 하는 것 같습니다.)

2022-06-30 07:03 UTC, otzslayer commented
> 변경된 코드에 대해 현재까지의 위 리뷰 내용(w/코멘트)에 동의합니다. 추가 코멘트가 하나 있습니다.
> 
> * models 폴더 내 스크립트 구현 관련 : 각 추천 모델들을 클래스로 구현했을 때 main.py를 어떻게 구성해서 모델을 선언할지가 정해지지 않아서 모델 클래스의 **init** 구성이 제각각이 될 수 있겠다는 생각이 들었습니다.  (지금의 경우도, encoder와 decoder를 클래스로 만들어서 AutoRec의 인자로 넣어주는 형태라면, main.py에서 encoder와 decoder 클래스를 선언해줘야 하는 것 같습니다.)

최대한 scikit-learn과 유사한 인터페이스를 가져가려고 합니다.

```
model = AutoRec(some_args)
model.fit(some_args)
model.predict(some_args)
```

그러다보니 최대한 모델을 선언할 때의 인자는 간단하게 가져가고 싶은거구요.

2022-07-01 01:05 UTC, otzslayer requested changes
위 내용 수정 반영 부탁드릴게요 :)
저도 바쁜 일이 좀 끝나면 바로 작업하겠습니다 ㅎㅎ

2022-07-18 12:18 UTC, closed without merging